//F01 Screen

const NAVIGATE_TO_LOGIN_SCREEN = 'Login';
const NAVIGATE_TO_REGISTER_SCREEN = 'Register';
const NAVIGATE_TO_FORGOT_PASSWORD = 'ForgotPassword';

//F02 Screen

const NAVIGATE_TO_HOME_SCREEN = 'Home';
const NAVIGATE_TO_TAB_SCREEN = 'BottomTabNavigation';
const NAVIGATE_TO_TRIP_SCREEN = 'Trip';
const NAVIGATE_TO_NOTIFICATION_SCREEN = 'Notification';
const NAVIGATE_TO_PERSONAL_SCREEN = 'Personal';
const NAVIGATE_TO_PERSONAL_INFORMATION_SCREEN = 'PersonalInformation';
const NAVIGATE_TO_CHANGE_PASSWORD = 'ChangePassword';
const NAVIGATE_TO_CREATE_TRIP = 'CreateTrip';
const NAVIGATE_TO_TRIP_DETAIL = 'TripDetail';
const NAVIGATE_TO_EDIT_TRIP = 'EditTrip';

export {
  NAVIGATE_TO_HOME_SCREEN,
  NAVIGATE_TO_LOGIN_SCREEN,
  NAVIGATE_TO_REGISTER_SCREEN,
  NAVIGATE_TO_FORGOT_PASSWORD,
  NAVIGATE_TO_TAB_SCREEN,
  NAVIGATE_TO_NOTIFICATION_SCREEN,
  NAVIGATE_TO_TRIP_SCREEN,
  NAVIGATE_TO_PERSONAL_SCREEN,
  NAVIGATE_TO_PERSONAL_INFORMATION_SCREEN,
  NAVIGATE_TO_CHANGE_PASSWORD,
  NAVIGATE_TO_CREATE_TRIP,
  NAVIGATE_TO_TRIP_DETAIL,
  NAVIGATE_TO_EDIT_TRIP,
};
