const NAVIGATE_TO_LOGIN_SCREEN = 'Login';
const NAVIGATE_TO_REGISTER_SCREEN = 'Register';
const NAVIGATE_TO_HOME_SCREEN = 'Home';

export {
  NAVIGATE_TO_HOME_SCREEN,
  NAVIGATE_TO_LOGIN_SCREEN,
  NAVIGATE_TO_REGISTER_SCREEN,
};
