//F01 Screen

const NAVIGATE_TO_LOGIN_SCREEN = 'Login';
const NAVIGATE_TO_REGISTER_SCREEN = 'Register';
const NAVIGATE_TO_FORGOT_PASSWORD = 'ForgotPassword';

//F02 Screen

const NAVIGATE_TO_HOME_SCREEN = 'Home';
const NAVIGATE_TO_TAB_SCREEN = 'BottomTabNavigation';
const NAVIGATE_TO_TRIP_SCREEN = 'Trip';
const NAVIGATE_TO_NOTIFICATION_SCREEN = 'Notification';
const NAVIGATE_TO_PERSONAL_SCREEN = 'Personal';
const NAVIGATE_TO_PERSONAL_INFORMATION_SCREEN = 'PersonalInformation';
const NAVIGATE_TO_CHANGE_PASSWORD = 'ChangePassword';
const NAVIGATE_TO_CREATE_TRIP = 'CreateTrip';
const NAVIGATE_TO_TRIP_DETAIL = 'TripDetail';
const NAVIGATE_TO_EDIT_TRIP = 'EditTrip';
const NAVIGATE_TO_ARRANGE_PLACE = 'ArrangePlace';
const NAVIGATE_TO_JOIN_TRIP = 'JoinTrip';
const NAVIGATE_TO_TRIP_MEMBER = 'TripMember';
const NAVIGATE_TO_MEMBER_INFO = 'MemberInfo';
const NAVIGATE_TO_ADD_DESTINATION = 'AddDestination';
const NAVIGATE_TO_DESTINATION_DETAIL = 'DestinationDetail';

export {
  NAVIGATE_TO_HOME_SCREEN,
  NAVIGATE_TO_LOGIN_SCREEN,
  NAVIGATE_TO_REGISTER_SCREEN,
  NAVIGATE_TO_FORGOT_PASSWORD,
  NAVIGATE_TO_TAB_SCREEN,
  NAVIGATE_TO_NOTIFICATION_SCREEN,
  NAVIGATE_TO_TRIP_SCREEN,
  NAVIGATE_TO_PERSONAL_SCREEN,
  NAVIGATE_TO_PERSONAL_INFORMATION_SCREEN,
  NAVIGATE_TO_CHANGE_PASSWORD,
  NAVIGATE_TO_CREATE_TRIP,
  NAVIGATE_TO_TRIP_DETAIL,
  NAVIGATE_TO_EDIT_TRIP,
  NAVIGATE_TO_ARRANGE_PLACE,
  NAVIGATE_TO_JOIN_TRIP,
  NAVIGATE_TO_TRIP_MEMBER,
  NAVIGATE_TO_MEMBER_INFO,
  NAVIGATE_TO_ADD_DESTINATION,
  NAVIGATE_TO_DESTINATION_DETAIL,
};
