//F01
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_FAIL = 'REGISTER_FAIL';

//F02
export const CHANGE_PERSONAL_INFORMATION = 'CHANGE_PERSONAL_INFORMATION';
export const CHANGE_PERSONAL_INFORMATION_SUCCESS =
  'CHANGE_PERSONAL_INFORMATION_SUCCESS';
export const CHANGE_PERSONAL_INFORMATION_LOADING =
  'CHANGE_PERSONAL_INFORMATION_LOADING';
export const CHANGE_PERSONAL_INFORMATION_FAIL =
  'CHANGE_PERSONAL_INFORMATION_FAIL';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
