//F01
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_FAIL = 'REGISTER_FAIL';

//F02
export const CHANGE_PERSONAL_INFORMATION = 'CHANGE_PERSONAL_INFORMATION';
export const CHANGE_PERSONAL_INFORMATION_SUCCESS =
  'CHANGE_PERSONAL_INFORMATION_SUCCESS';
export const CHANGE_PERSONAL_INFORMATION_LOADING =
  'CHANGE_PERSONAL_INFORMATION_LOADING';
export const CHANGE_PERSONAL_INFORMATION_FAIL =
  'CHANGE_PERSONAL_INFORMATION_FAIL';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const GET_ALL_TRIP = 'GET_ALL_TRIP';
export const GET_ALL_TRIP_SUCCESS = 'GET_ALL_TRIP_SUCCESS';
export const GET_ALL_TRIP_LOADING = 'GET_ALL_TRIP_LOADING';
export const GET_ALL_TRIP_FAIL = 'GET_ALL_TRIP_FAIL';

export const CREATE_TRIP = 'CREATE_TRIP';
export const CREATE_TRIP_SUCCESS = 'CREATE_TRIP_SUCCESS';
export const CREATE_TRIP_LOADING = 'CREATE_TRIP_LOADING';
export const CREATE_TRIP_FAIL = 'CREATE_TRIP_FAIL';

export const EDIT_TRIP = 'EDIT_TRIP';
export const EDIT_TRIP_SUCCESS = 'EDIT_TRIP_SUCCESS';
export const EDIT_TRIP_LOADING = 'EDIT_TRIP_LOADING';
export const EDIT_TRIP_FAIL = 'EDIT_TRIP_FAIL';

export const JOIN_TRIP = 'JOIN_TRIP';
export const JOIN_TRIP_SUCCESS = 'JOIN_TRIP_SUCCESS';
export const JOIN_TRIP_LOADING = 'JOIN_TRIP_LOADING';
export const JOIN_TRIP_FAIL = 'JOIN_TRIP_FAIL';

export const GET_MEMBER_INFO = 'GET_MEMBER_INFO';
export const GET_MEMBER_INFO_SUCCESS = 'GET_MEMBER_INFO_SUCCESS';
export const GET_MEMBER_INFO_LOADING = 'GET_MEMBER_INFO_LOADING';
export const GET_MEMBER_INFO_FAIL = 'GET_MEMBER_INFO_FAIL';

export const ADD_DESTINATION = 'ADD_DESTINATION';
export const ADD_DESTINATION_SUCCESS = 'ADD_DESTINATION_SUCCESS';
export const ADD_DESTINATION_LOADING = 'ADD_DESTINATION_LOADING';
export const ADD_DESTINATION_FAIL = 'ADD_DESTINATION_FAIL';

export const EDIT_DESTINATION = 'EDIT_DESTINATION';
export const EDIT_DESTINATION_SUCCESS = 'EDIT_DESTINATION_SUCCESS';
export const EDIT_DESTINATION_LOADING = 'EDIT_DESTINATION_LOADING';
export const EDIT_DESTINATION_FAIL = 'EDIT_DESTINATION_FAIL';
